/**
 * qa/unity/compile.ts — compile a Unity project's C# WITHOUT launching Unity.
 *
 * WHY THIS EXISTS ALONGSIDE BATCH MODE. `Unity -batchmode` is authoritative and unusable in the loop it
 * matters for: it needs the project lock (so it cannot run while the editor is open — which is exactly
 * when someone is working), it needs a licence, and a cold import of a real project is minutes. Meanwhile
 * the editor has already written down everything a compiler needs, in the `.sln`/`.csproj` files it
 * generates: the source list, the reference DLLs with absolute paths, the defines, the language version.
 * Compiling from those takes seconds, needs no lock, and works with the editor open.
 *
 * WHAT A UNITY-GENERATED PROJECT NEEDS in order to build outside Unity — the honest list, because each
 * item is a way this returns "not verified" rather than an answer:
 *
 *   1. THE FILES MUST EXIST. `.sln`/`.csproj` are generated by the editor (the Rider/Visual Studio
 *      package) and are gitignored, so a fresh clone has none. Unity regenerates them on open, or with
 *      `-executeMethod UnityEditor.SyncVS.SyncSolution`.
 *   2. THE REFERENCES MUST RESOLVE. Those files carry ABSOLUTE HintPaths into the editor install and into
 *      `Library/ScriptAssemblies`. They are correct on the machine that generated them and wrong on any
 *      other — a different Unity version, a different install location, or a clone that has never been
 *      opened. Missing references are reported by path, not swallowed.
 *   3. A COMPILER. In order: the system `dotnet`/`msbuild` if present (they build the solution as a
 *      whole), else Roslyn as SHIPPED BY UNITY — `csc.dll` under the editor's `Tools/Roslyn`, run with
 *      the editor's own .NET runtime. That last one is what makes this work on a machine with no .NET SDK
 *      installed at all, which is the normal state of a Mac that only has Unity.
 *
 * THE OUTPUT IS ALWAYS `error CS…` LINES. Every one of these compilers prints the same shape, which is
 * why the caller can treat them interchangeably and why the parser lives in one place.
 *
 * READ-ONLY-ISH: it writes only into a temp directory (`-out:` and the response file) and never touches
 * `Library/`, so it cannot disturb an open editor.
 */

import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, isAbsolute, join, resolve } from 'node:path';

export interface CsProject {
  path: string;
  assembly: string;
  /** Absolute paths of every `<Compile Include=…>`. */
  sources: string[];
  /** Absolute paths of every resolvable `<Reference><HintPath>`, plus bare `<Reference Include>` names. */
  references: string[];
  /** HintPaths that do NOT exist on this machine — the "generated elsewhere" symptom. */
  missingReferences: string[];
  defines: string[];
  langVersion: string | null;
  unsafeCode: boolean;
  /** Unity compiles against its own corlib; the generated file says so and csc must be told. */
  noStdLib: boolean;
}

export interface CompileAttempt {
  /** What was run, in a form the operator could paste into a shell. */
  command: string;
  /** `error CS…` lines, verbatim and de-duplicated. */
  errors: string[];
  /** Set when the compile could not be attempted or its result cannot be trusted. */
  unverified?: string;
  /** Whatever the tool said, tail-trimmed, for an unverified result. */
  output?: string;
}

/** `Foo.cs(12,9): error CS1002: ; expected` — the shape every C# compiler and Unity's own log print. */
export const CS_ERROR_RE = /(\S+\.cs)\((\d+),(\d+)\):\s*error\s+(CS\d+):\s*(.+)/g;

export function parseCsErrors(text: string): string[] {
  const out = [...text.matchAll(CS_ERROR_RE)].map((m) => `${m[1]}(${m[2]},${m[3]}): ${m[4]}: ${m[5]}`.trim());
  return [...new Set(out)];
}

/** Every `.sln` and `.csproj` Unity generated at the project root (it does not nest them). */
export function generatedProjects(root: string): { sln: string | null; csprojs: string[] } {
  let entries: string[] = [];
  try { entries = readdirSync(root); } catch { return { sln: null, csprojs: [] }; }
  const sln = entries.filter((e) => e.toLowerCase().endsWith('.sln')).sort()[0] ?? null;
  const csprojs = entries.filter((e) => e.toLowerCase().endsWith('.csproj')).sort().map((e) => join(root, e));
  return { sln: sln ? join(root, sln) : null, csprojs };
}

const attr = (tag: string, name: string): string | null => {
  const m = new RegExp(`${name}\\s*=\\s*"([^"]*)"`, 'i').exec(tag);
  return m ? m[1] : null;
};

/**
 * Read one generated `.csproj`.
 *
 * A REGEX READER, NOT AN XML PARSER, for the same reason the rest of this repo uses one: ayin ships no
 * XML dependency, and the shape consumed here is four element kinds written by a generator, not
 * hand-authored markup. What it must never do is silently produce an EMPTY source list from a file whose
 * shape it did not understand — that would compile nothing and report success. So the caller checks
 * `sources.length` and treats zero as unverified.
 */
export function readCsproj(path: string): CsProject {
  const xml = readFileSync(path, 'utf-8');
  const dir = dirname(path);
  const abs = (p: string): string => (isAbsolute(p) ? p : resolve(dir, p.replace(/\\/g, '/')));

  const sources: string[] = [];
  for (const m of xml.matchAll(/<Compile\b([^>]*)\/?>/gi)) {
    const inc = attr(m[1], 'Include');
    if (inc) sources.push(abs(inc));
  }

  const references: string[] = [];
  const missingReferences: string[] = [];
  // `<Reference Include="X"><HintPath>…</HintPath></Reference>` — the HintPath is what actually resolves.
  for (const m of xml.matchAll(/<Reference\b([^>]*)>([\s\S]*?)<\/Reference>/gi)) {
    const hint = /<HintPath>([\s\S]*?)<\/HintPath>/i.exec(m[2]);
    if (hint) {
      const p = abs(hint[1].trim());
      if (existsSync(p)) references.push(p);
      else missingReferences.push(p);
      continue;
    }
    const inc = attr(m[1], 'Include');
    if (inc) references.push(inc); // a framework reference by name; csc resolves it or says it cannot
  }
  // A ProjectReference is another generated csproj — its DLL is in Library/ScriptAssemblies once Unity has
  // compiled it, and that is what a per-assembly compile needs on the reference path.
  for (const m of xml.matchAll(/<ProjectReference\b([^>]*)>/gi)) {
    const inc = attr(m[1], 'Include');
    if (!inc) continue;
    const name = basename(inc.replace(/\\/g, '/')).replace(/\.csproj$/i, '');
    const dll = resolve(dir, 'Library', 'ScriptAssemblies', `${name}.dll`);
    if (existsSync(dll)) references.push(dll);
    else missingReferences.push(dll);
  }

  const defines = (/<DefineConstants>([\s\S]*?)<\/DefineConstants>/i.exec(xml)?.[1] ?? '')
    .split(';').map((d) => d.trim()).filter(Boolean);
  const langVersion = /<LangVersion>([\s\S]*?)<\/LangVersion>/i.exec(xml)?.[1]?.trim() ?? null;
  const unsafeCode = /<AllowUnsafeBlocks>\s*true\s*<\/AllowUnsafeBlocks>/i.test(xml);
  const noStdLib = /<NoStdLib>\s*true\s*<\/NoStdLib>/i.test(xml);
  const assembly = /<AssemblyName>([\s\S]*?)<\/AssemblyName>/i.exec(xml)?.[1]?.trim()
    ?? basename(path).replace(/\.csproj$/i, '');

  return { path, assembly, sources, references, missingReferences, defines, langVersion, unsafeCode, noStdLib };
}

/** Which generated csproj owns a given source file — the assembly a changed `.cs` belongs to. */
export function projectsCovering(projects: CsProject[], sources: string[]): CsProject[] {
  const want = new Set(sources.map((s) => resolve(s)));
  return projects.filter((p) => p.sources.some((s) => want.has(resolve(s))));
}

const which = (cmd: string): boolean =>
  spawnSync(process.platform === 'win32' ? 'where' : 'which', [cmd], { stdio: 'ignore' }).status === 0;

/**
 * Roslyn AS SHIPPED BY UNITY, and the runtime to run it with.
 *
 * This is the piece that makes a compile possible on a machine with no .NET SDK — the normal state of a
 * Mac that only has Unity. Unity keeps a full Roslyn under the editor and a .NET runtime beside it; the
 * layout differs by version and platform, so every known location is tried and the first hit wins. Paths
 * are DERIVED from the editor path the caller already resolved (`unityBinary`), never written down for a
 * particular machine.
 */
export function unityCsc(unityExecutable: string): { runtime: string; cscDll: string } | null {
  // …/Unity.app/Contents/MacOS/Unity → …/Unity.app/Contents
  // …/Editor/Unity(.exe)             → …/Editor/Data
  const contents = process.platform === 'darwin'
    ? resolve(dirname(unityExecutable), '..')
    : resolve(dirname(unityExecutable), 'Data');
  const cscCandidates = [
    join(contents, 'Tools', 'Roslyn', 'csc.dll'),
    join(contents, 'Tools', 'RoslynScripts', 'csc.dll'),
    join(contents, 'Tools', 'Roslyn', 'csc'),
  ];
  const runtimeCandidates = [
    join(contents, 'NetCoreRuntime', 'dotnet'),
    join(contents, 'Tools', 'netcorerun', 'netcorerun'),
    join(contents, 'MonoBleedingEdge', 'bin', 'mono'),
  ];
  const cscDll = cscCandidates.find(existsSync);
  const runtime = runtimeCandidates.find(existsSync);
  if (!cscDll || !runtime) return null;
  return { runtime, cscDll };
}

/**
 * Compile ONE generated project with csc, into a temp directory.
 *
 * A RESPONSE FILE, not a command line: a Unity assembly is routinely a thousand source files and several
 * hundred references, which is far past every platform's argv limit. `@file` is how the C# compiler has
 * always taken that, and it is also what makes the attempt reproducible — the file is quoted in the
 * report so the operator can run the same thing by hand.
 */
export function compileWithCsc(
  project: CsProject,
  csc: { runtime: string; cscDll: string },
  timeoutMs: number,
): CompileAttempt {
  if (project.sources.length === 0) {
    return { command: '(none)', errors: [], unverified: `${basename(project.path)} lists no <Compile Include> items — the file's shape was not understood, so nothing was compiled` };
  }
  const dir = mkdtempSync(join(tmpdir(), 'ayin-csc-'));
  const rsp = join(dir, 'csc.rsp');
  const out = join(dir, `${project.assembly}.dll`);
  const lines = [
    '-target:library',
    `-out:${out}`,
    '-nologo',
    '-nostdlib+',
    ...(project.noStdLib ? [] : ['-nostdlib-']),
    ...(project.unsafeCode ? ['-unsafe+'] : []),
    ...(project.langVersion ? [`-langversion:${project.langVersion}`] : []),
    ...(project.defines.length ? [`-define:${project.defines.join(';')}`] : []),
    ...project.references.map((r) => `-reference:${r}`),
    ...project.sources,
  ];
  writeFileSync(rsp, lines.join('\n'));
  const command = `${basename(csc.runtime)} ${basename(csc.cscDll)} @${rsp}`;
  try {
    let output = '';
    try {
      output = execFileSync(csc.runtime, [csc.cscDll, `@${rsp}`], {
        encoding: 'utf-8', timeout: timeoutMs, stdio: ['ignore', 'pipe', 'pipe'],
      });
    } catch (e) {
      const err = e as { stdout?: string; stderr?: string; signal?: string };
      output = `${err.stdout ?? ''}${err.stderr ?? ''}`;
      if (err.signal === 'SIGTERM') {
        return { command, errors: [], unverified: 'the csc compile timed out', output: tail(output) };
      }
    }
    const errors = parseCsErrors(output);
    if (errors.length) return { command, errors };
    // No CS errors and no DLL means the compiler failed for a reason of its own (a bad reference path, a
    // runtime it could not start) — that is unverified, never a pass.
    if (!existsSync(out)) {
      return { command, errors: [], unverified: 'csc produced no assembly and reported no C# errors', output: tail(output) };
    }
    return { command, errors: [] };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * Build the whole SOLUTION with the system toolchain, when there is one.
 *
 * Tried before csc because it is the operator's own build: same targets, same order, same result as their
 * IDE. Unity's generated projects are legacy-format, so `dotnet build` may refuse them outright — that is
 * detected (an MSB/NETSDK complaint with no C# errors) and reported as unverified so the caller falls
 * through to csc rather than calling a tooling mismatch a compile failure.
 */
export function buildSolution(sln: string, timeoutMs: number): CompileAttempt | null {
  const tool = which('dotnet') ? 'dotnet' : which('msbuild') ? 'msbuild' : null;
  if (!tool) return null;
  const args = tool === 'dotnet'
    ? ['build', sln, '-v:quiet', '--nologo', '-p:Configuration=Debug']
    : [sln, '/v:quiet', '/nologo', '/p:Configuration=Debug'];
  const command = `${tool} ${args.join(' ')}`;
  let output = '';
  try {
    output = execFileSync(tool, args, { encoding: 'utf-8', timeout: timeoutMs, cwd: dirname(sln), stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    const err = e as { stdout?: string; stderr?: string; signal?: string };
    output = `${err.stdout ?? ''}${err.stderr ?? ''}`;
    if (err.signal === 'SIGTERM') return { command, errors: [], unverified: `${tool} timed out`, output: tail(output) };
  }
  const errors = parseCsErrors(output);
  if (errors.length) return { command, errors };
  // MSB4025 / NETSDK1013 / "is not supported by dotnet build": the toolchain cannot read Unity's legacy
  // project format. Not a compile result at all.
  if (/\b(MSB\d{4}|NETSDK\d{4})\b|not supported by/i.test(output)) {
    return { command, errors: [], unverified: `${tool} could not read Unity's generated project format`, output: tail(output) };
  }
  if (/\berror\b/i.test(output)) {
    return { command, errors: [], unverified: `${tool} reported errors that are not C# compile errors`, output: tail(output) };
  }
  return { command, errors: [] };
}

function tail(text: string, n = 6): string {
  return text.split('\n').map((l) => l.trimEnd()).filter(Boolean).slice(-n).join('\n');
}

/** Newest mtime among a project's sources — for reporting how current the compiled result is. */
export function newestSource(project: CsProject): number {
  let newest = 0;
  for (const s of project.sources) {
    try { newest = Math.max(newest, statSync(s).mtimeMs); } catch { /* listed but gone */ }
  }
  return newest;
}
