#!/usr/bin/env node
/**
 * unity-compile — compile a Unity project's C# from its GENERATED `.sln`/`.csproj`, with no editor launch.
 *
 *     node tool/unity-compile.mjs [projectPath] [--verbose]
 *
 * The same code path the QA gate uses (`dist/executors/qa/unity/compile.js`), exposed as a command so it
 * can be run and read by a human on the machine that has Unity. That matters more than usual here: this
 * box has no Unity, no .NET SDK and no generated project files, so the parsing and the fallbacks are
 * unit-tested but the actual compile is not — running this once on the real machine is what turns "should
 * work" into "works", and its output says exactly which of the paths below was taken.
 *
 * WHAT IT NEEDS, and what each missing piece looks like in the output:
 *   · `.sln`/`.csproj` at the project root — generated by the editor (Rider/Visual Studio package) and
 *     gitignored, so a fresh clone has none. Unity writes them on open.
 *   · reference paths that resolve HERE — they are absolute and belong to the machine that generated them.
 *   · a compiler: `dotnet`/`msbuild` if installed, else Roslyn as shipped inside the Unity install.
 *
 * Exit code: 0 compiled clean · 1 C# errors (printed) · 2 could not be verified (reason printed).
 */

import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
process.argv.push('-p'); // never open a TUI from a script

const args = process.argv.slice(2).filter((a) => a !== '-p');
const verbose = args.includes('--verbose');
const projectPath = resolve(args.find((a) => !a.startsWith('-')) ?? process.cwd());

const {
  buildSolution, compileWithCsc, generatedProjects, projectsCovering, readCsproj, unityCsc,
} = await import(`file://${join(ROOT, 'dist', 'executors', 'qa', 'unity', 'compile.js')}`);
const { unityBinary } = await import(`file://${join(ROOT, 'dist', 'testrun', 'run.js')}`);
const { unityVersion, isUnityProject } = await import(`file://${join(ROOT, 'dist', 'testrun', 'asmdef.js')}`);

const say = (...a) => console.log(...a);
const die = (code, why) => { say(`\n${why}`); process.exit(code); };

if (!isUnityProject(projectPath)) {
  die(2, `not a Unity project: ${projectPath} has no ProjectSettings/ProjectVersion.txt`);
}
say(`project   ${projectPath}`);
say(`unity     ${unityVersion(projectPath) ?? '(version unknown)'}`);

const { sln, csprojs } = generatedProjects(projectPath);
say(`sln       ${sln ?? '(none)'}`);
say(`csproj    ${csprojs.length ? `${csprojs.length} found` : '(none)'}`);
if (!sln && csprojs.length === 0) {
  die(2, 'NOT VERIFIED: no generated project files. Open the project in Unity once (it writes them), or run\n'
    + '  Unity -batchmode -quit -projectPath <path> -executeMethod UnityEditor.SyncVS.SyncSolution');
}

const projects = csprojs.map((p) => {
  try { return readCsproj(p); } catch (e) { say(`  ! could not read ${p}: ${e.message}`); return null; }
}).filter(Boolean);

for (const p of projects) {
  const flag = p.missingReferences.length ? ` · ${p.missingReferences.length} MISSING ref(s)` : '';
  say(`  ${p.assembly}: ${p.sources.length} source(s), ${p.references.length} ref(s)${flag}`
    + `${p.langVersion ? `, C# ${p.langVersion}` : ''}${p.defines.length ? `, ${p.defines.length} define(s)` : ''}`);
  if (verbose && p.missingReferences.length) for (const m of p.missingReferences.slice(0, 8)) say(`      missing: ${m}`);
  if (verbose) for (const d of p.defines.slice(0, 8)) say(`      define: ${d}`);
}

const missing = projects.flatMap((p) => p.missingReferences);
if (projects.length && missing.length === projects.flatMap((p) => p.references.concat(p.missingReferences)).length) {
  die(2, 'NOT VERIFIED: every reference path is missing on this machine — these files were generated elsewhere.\n'
    + 'Open the project in Unity once to regenerate them.');
}

const TIMEOUT = 20 * 60_000;

// 1. the operator's own toolchain, if any — the same build their IDE runs
if (sln) {
  const built = buildSolution(sln, TIMEOUT);
  if (built) {
    say(`\n$ ${built.command}`);
    if (built.errors.length) {
      for (const e of built.errors.slice(0, 20)) say(`  ${e}`);
      die(1, `DOES NOT COMPILE: ${built.errors.length} C# error(s)`);
    }
    if (!built.unverified) die(0, 'COMPILES: no C# errors');
    say(`  → ${built.unverified}`);
    if (built.output) for (const l of built.output.split('\n')) say(`    ${l}`);
    say('  falling through to Unity\'s own Roslyn…');
  } else {
    say('\nno dotnet/msbuild on PATH — using Unity\'s own Roslyn');
  }
}

// 2. Roslyn from inside the Unity install — works with no .NET SDK at all
const unity = unityBinary(projectPath);
if (!unity) {
  die(2, 'NOT VERIFIED: no Unity install found for this project\'s version.\n'
    + 'On macOS it is /Applications/Unity/Hub/Editor/<version>/Unity.app/Contents/MacOS/Unity —\n'
    + 'point ayin at yours with `/set unity-path <path>`.');
}
say(`\nunity exe ${unity}`);
const csc = unityCsc(unity);
if (!csc) {
  die(2, `NOT VERIFIED: no Roslyn found inside ${unity} — the layout of this Unity version is not one of the known ones.\n`
    + 'Run with --verbose and report what is under <Unity.app>/Contents/Tools so it can be added.');
}
say(`csc       ${csc.cscDll}`);
say(`runtime   ${csc.runtime}`);

const targets = projects.length ? projects : [];
if (!targets.length) die(2, 'NOT VERIFIED: no readable .csproj to compile');

let errors = [];
let unverified = [];
for (const p of targets) {
  const r = compileWithCsc(p, csc, TIMEOUT);
  say(`\n$ ${r.command}`);
  if (r.errors.length) {
    errors = errors.concat(r.errors);
    for (const e of r.errors.slice(0, 20)) say(`  ${e}`);
  } else if (r.unverified) {
    unverified.push(`${p.assembly}: ${r.unverified}`);
    say(`  → ${r.unverified}`);
    if (r.output) for (const l of r.output.split('\n')) say(`    ${l}`);
  } else {
    say(`  ${p.assembly}: no C# errors`);
  }
}

if (errors.length) die(1, `DOES NOT COMPILE: ${new Set(errors).size} C# error(s) across ${targets.length} assembl(y/ies)`);
if (unverified.length === targets.length) die(2, `NOT VERIFIED:\n  ${unverified.join('\n  ')}`);
die(0, `COMPILES: ${targets.length} assembl(y/ies), no C# errors`);
