/**
 * Arduino QA executor — the gate for embedded work.
 *
 * TWO PROBLEMS THIS FIXES, both measured rather than theorised.
 *
 * 1. THE GATE WAS FAILING WORK IT WAS ABOUT TO FIX ITSELF. The wiring criterion asks whether the
 *    reply references a rendered `.wiring.puml`. The diagram was generated by the hook that runs
 *    AFTER a QA pass succeeds — so on pass 1 the file did not exist, the judge could not find it, the
 *    criterion failed, and a full fix pass (two LLM calls, plus the agent's own round to "fix" it)
 *    was spent arriving where the next line of code was going to arrive anyway. `prepare()` runs
 *    BEFORE the judge and produces the artifact the criteria are about. That single reordering is the
 *    largest share of the "Arduino QA is slow and always fails" complaint.
 *
 * 2. THE GATE WAS ASKING A LANGUAGE MODEL TO REVIEW C++ THAT A COMPILER WAS SITTING RIGHT THERE TO
 *    CHECK. `arduino-cli compile` gives the real answer with the real line number in a couple of
 *    seconds. Now it runs as a probe, and its result is handed to the judge as a fact. A model
 *    guessing at whether a sketch builds is both slower and worse.
 *
 * The remaining facts are the ones reading cannot establish: whether the deliverables are on disk,
 * whether the generated PlantUML actually parses, and whether `analogWrite` is being called on a pin
 * that has no hardware PWM — a bug that compiles cleanly, looks correct in review, and produces an
 * LED with eight colours instead of sixteen million.
 */

import { existsSync, mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { log } from '../../../log.js';
import { extractPinUsage, findSketches } from '../../../tools/arduino-explain.js';
import { regenerateTouchedDiagrams, validatePumlFile, isGeneratedPuml, wiringPumlPath, diagramGrounding } from '../../../tools/arduino-diagram.js';
import { boardFromFqbn, compileSketch, projectFqbn, isPwmPin, pwmPins } from '../../../tools/arduino-toolchain.js';
import type { ChangedFile } from '../../../qa/probes.js';
import { checkDeliverables, renderDeliverables, readmeSubstance } from '../../deliverables.js';
import type { ExecutorConfig, PrepareResult, ProbeFact, ProjectContext, QaExecutor } from '../../types.js';
import { arduinoPlanExecutor } from '../../plan/arduino/index.js';

const config: ExecutorConfig = {
  id: 'arduino', kind: 'qa', projectTypes: ['arduino'], priority: 100,
  description: 'Arduino QA — regenerate the wiring diagram first, then compile-check, validate the diagram and assert deliverables.',
};

/** Sketches this turn touched, or every sketch when the turn touched none by name. */
function relevantSketches(root: string, files: ChangedFile[]): string[] {
  const touched = files.filter((f) => f.exists && /\.(ino|pde)$/i.test(f.path)).map((f) => f.path);
  if (touched.length) return touched;
  return findSketches(root).map((s) => s.path);
}

// `wiringPumlPath` and the "is this diagram current and actually generated" test both live in
// `arduino-diagram.ts` now — see `isDiagramCurrent`. They were here, which meant every OTHER caller
// of `regenerateTouchedDiagrams` re-spent a grounding LLM call and any new caller had to remember to
// reimplement the check. It is a property of the regeneration operation, not of this executor.

export const arduinoQaExecutor: QaExecutor = {
  config,

  /**
   * Produce the wiring diagram BEFORE anything is judged.
   *
   * BOUNDED BY MTIME, not by a flag. This runs on every QA pass, and a QA turn can have three — so a
   * naive implementation would spend one grounding LLM call per sketch PER PASS, three times the
   * cost of the thing it replaced. But it cannot simply run once either: the whole point of a fix
   * pass is that the sketch CHANGED, and a diagram generated from the previous version is worse than
   * none (it looks current and is not). The honest test is on disk — regenerate only when the sketch
   * is newer than the diagram beside it. Pass 1 generates; pass 2 after a real edit regenerates;
   * pass 2 after an edit somewhere else costs nothing.
   */
  async prepare(ctx: ProjectContext, files: ChangedFile[]): Promise<PrepareResult> {
    const produced: string[] = [];
    const notes: string[] = [];
    let handled = new Set<string>();
    try {
      const regen = await regenerateTouchedDiagrams(ctx.root, files);
      if (regen) {
        handled = regen.regeneratedPaths;
        for (const r of regen.results) {
          if (r.svgPath) produced.push(r.svgPath);
          produced.push(r.pumlPath);
          if (!r.verified) notes.push(`${r.sketch}: the generated PlantUML did not pass \`plantuml -syntax\``);
        }
      }
    } catch (err) {
      // A diagram that cannot be produced is a fact the probe below will report. It must not take
      // the gate down — a broken gate is worse than the bugs it catches.
      log('WARN', 'arduino_qa_prepare_failed', { error: err instanceof Error ? err.message : String(err) });
      notes.push(`wiring diagram generation failed: ${err instanceof Error ? err.message : String(err)}`);
    }
    return { produced, handled, notes };
  },

  async probe(ctx: ProjectContext, files: ChangedFile[]): Promise<ProbeFact[]> {
    const facts: ProbeFact[] = [];
    const { fqbn } = projectFqbn(ctx.root);
    const board = boardFromFqbn(fqbn);

    // ── deliverables ────────────────────────────────────────────────
    const statuses = checkDeliverables(ctx.root, arduinoPlanExecutor.deliverables(ctx));
    const d = renderDeliverables(ctx.root, statuses);
    facts.push({ key: 'deliverables', ok: d.ok, detail: d.detail });
    // Existence is not substance. `scaffold()` guarantees a README file; this asks whether it says
    // anything — an untouched stub passes every existence check while documenting nothing.
    const rm = readmeSubstance(ctx.root);
    facts.push({ key: 'readme-substance', ok: rm.ok, detail: rm.detail });

    const sketches = relevantSketches(ctx.root, files);

    // ── does it actually build? ─────────────────────────────────────
    let buildPath: string | null = null;
    try {
      buildPath = mkdtempSync(join(tmpdir(), 'ayin-arduino-build-'));
      for (const sketch of sketches.slice(0, 3)) {
        const result = await compileSketch(dirname(sketch), fqbn, buildPath);
        facts.push({
          key: `compile:${basename(sketch)}`,
          // A skipped compile is not a failure — it is an unknown, and must never read as a pass the
          // judge can lean on. `ok` stays true so it does not fail the change; the detail says plainly
          // that nothing was verified.
          ok: result.ok,
          detail: result.skipped
            ? `${basename(sketch)}: ${result.reason}`
            : `${basename(sketch)}: ${result.reason}${result.ok ? '' : `\n${result.output}`}`,
        });
      }
    } finally {
      if (buildPath) { try { rmSync(buildPath, { recursive: true, force: true }); } catch { /* temp dir, best effort */ } }
    }

    // ── is the generated PlantUML actually valid? ───────────────────
    for (const sketch of sketches.slice(0, 3)) {
      const puml = wiringPumlPath(sketch);
      if (!existsSync(puml)) {
        facts.push({
          key: `diagram:${basename(sketch)}`, ok: false,
          detail: `${basename(puml)} does not exist — run the arduino_diagram tool; wiring must be SHOWN, not described in prose`,
        });
        continue;
      }
      // Generated-or-hand-written FIRST: a hand-written diagram that happens to parse is a worse
      // outcome than one that does not, because it passes every other check while being ungrounded.
      let generated = false;
      try { generated = isGeneratedPuml(readFileSync(puml, 'utf8')); } catch { /* reported below */ }
      if (!generated) {
        facts.push({
          key: `diagram:${basename(sketch)}`, ok: false,
          detail: `${basename(puml)} was NOT generated by the arduino_diagram tool — it lacks the tool's provenance stamp, so it was written by hand. A hand-drawn wiring diagram is ungrounded: nothing checked its pinouts against the component catalog, and a plausible wrong pinout is worse than no diagram because someone will wire it. Delete it and run arduino_diagram.`,
        });
        continue;
      }
      // GROUNDED NOTHING is a distinct failure from "missing" or "invalid", and it is the one that
      // looks fine. See `diagramGrounding`.
      // EXHAUSTED, not merely "grounded nothing" — a sketch driving only LED_BUILTIN has no external
      // part, so an all-unknown diagram is the correct and honest answer there. The generator records
      // which happened; see `GroundingResult.exhausted`.
      const g = diagramGrounding(readFileSync(puml, 'utf8'));
      if (g.exhausted) {
        facts.push({
          key: `diagram:${basename(sketch)}`, ok: false,
          detail: `${basename(puml)} exists and parses, but its component-grounding call EXHAUSTED its retries — every pin came back "unknown", so the diagram shows bare pins with no parts, no series resistors and no ground. Rerun the arduino_diagram tool.`,
        });
        continue;
      }
      const v = await validatePumlFile(puml);
      facts.push({
        key: `diagram:${basename(sketch)}`, ok: v.ok,
        detail: v.ok
          ? `${basename(puml)} was generated by arduino_diagram and PARSES (\`plantuml -syntax\` → ${v.kind ?? 'ok'})${existsSync(puml.replace(/\.puml$/, '.svg')) ? ', rendered .svg beside it' : ', NOT yet rendered to .svg'}`
          : `${basename(puml)} exists but is INVALID PlantUML: ${v.error}`,
      });
    }

    // ── PWM misuse: compiles clean, silently wrong ──────────────────
    const pwmProblems: string[] = [];
    for (const sketch of sketches.slice(0, 3)) {
      let source = '';
      try { source = readFileSync(sketch, 'utf8'); } catch { continue; }
      for (const pin of extractPinUsage(source)) {
        if (!pin.calls.includes('analogWrite')) continue;
        if (!/^\d{1,2}$/.test(pin.resolved)) continue; // unresolved constant — cannot judge it
        if (!isPwmPin(board, pin.resolved)) {
          pwmProblems.push(`${basename(sketch)}: analogWrite() on pin ${pin.resolved}${pin.raw !== pin.resolved ? ` (${pin.raw})` : ''}, which has NO hardware PWM on ${board}`);
        }
      }
    }
    if (board !== 'other') {
      facts.push({
        key: 'pwm-pins',
        ok: pwmProblems.length === 0,
        detail: pwmProblems.length
          ? `${pwmProblems.join('; ')}. PWM pins on ${board}: ${pwmPins(board).join(', ')}. This COMPILES but the pin can only be fully on or fully off — move the channel to a PWM pin.`
          : `every analogWrite() target is a PWM-capable pin on ${board} (${pwmPins(board).join(', ')})`,
      });
    }

    return facts;
  },

  criteria(_ctx: ProjectContext, _files: ChangedFile[], facts: ProbeFact[]): string[] {
    const ids = ['arduino-sketch-naming', 'arduino-quality', 'arduino-deliverables'];
    // The wiring criterion is only meaningful once a diagram could exist. `prepare()` has already
    // run by the time this is called, so a missing diagram here is a real gap, not a race.
    if (facts.some((f) => f.key.startsWith('diagram:'))) ids.push('arduino-wiring-diagram');
    if (facts.some((f) => f.key.startsWith('compile:'))) ids.push('arduino-compiles');
    return ids;
  },
};
